version: 0.2
        
phases:
  install:
    on-failure: ABORT
    commands: 
      - echo "Install"
      - curl https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - bash ./dotnet-install.sh -c 5.0
      - rm ./dotnet-install.sh
    finally:
      - echo "Install done"
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Testing"
      - dotnet test
    finally:
      - echo "Testing Done"
  build:
    on-failure: ABORT
    commands:
      - echo "Docker build"
      - docker build -t codepipeline-dojo .
    finally:
      - echo "Docker build done"
  post_build:
    on-failure: ABORT
    commands:
      - echo "Pushing"
      - echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION, AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID, TASKDEF_NAME=$TASKDEF_NAME"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - docker tag codepipeline-dojo:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/codepipeline-dojo:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/codepipeline-dojo:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $TASKDEF_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/codepipeline-dojo:latest > imagedefinitions.json
    finally:
      - echo "Pushing done"
post_build:
    commands:
      
artifacts:
  files: 
    - imagedefinitions.json
    - appspec.yml
